// Copyright 2005-2011 Mentor Graphics Corporation.  All rights reserved.
//

var mLibraryList = new Array();
   mLibraryList.push(["Calibre 3DSTACK Quick Reference","calbr_3dstack_qref","pdf"] );
   mLibraryList.push(["Calibre Chip-Level Verification Quick Reference","calbr_chip_verification_qref","pdf"] );
   mLibraryList.push(["Calibre DESIGNrev Key Definitions Quick Reference","calbr_drv_keydef_qref","pdf"] );
   mLibraryList.push(["Calibre FDI Mapping Quick Reference","calbr_fdi_map_qref","pdf"] );
   mLibraryList.push(["Calibre Interactive (New GUI) Quick Reference","calbr_interactive_n_qref","pdf"] );
   mLibraryList.push(["Calibre RVE for DRC Quick Reference","calbr_drcrve_qref","pdf"] );
   mLibraryList.push(["Calibre RVE for LVS Quick Reference","calbr_lvsrve_qref","pdf"] );
   mLibraryList.push(["Calibre RVE for PERC Quick Reference","calbr_percrve_qref","pdf"] );
   mLibraryList.push(["Calibre RealTime Digital in Cadence Innovus Quick Reference","calbr_realtime_innovus_qref","pdf"] );
   mLibraryList.push(["Calibre RealTime Digital in Synopsys IC Compiler II Quick Reference","calbr_realtime_icc2_qref","pdf"] );
   mLibraryList.push(["Calibre RealTime Integration to Cadence Virtuoso Quick Reference","calbr_realtime_virtuoso_qref","pdf"] );
   mLibraryList.push(["Calibre RealTime Integration to Synopsys Laker Quick Reference","calbr_realtime_laker_qref","pdf"] );
   mLibraryList.push(["Calibre eqDRC Quick Reference","calbr_eqdrc_qref","pdf"] );
   mLibraryList.push(["Calibre xACT Quick Reference","xact_qref","pdf"] );
   mLibraryList.push(["Calibre PDF Quick Reference","calbr_pdf_qref","pdf"] );
   mLibraryList.push(["Calibre® 3DSTACK User’s Manual","calbr_3dstack_user"] );
   mLibraryList.push(["Calibre® Administrator’s Guide","calbr_admin_gd"] );
   mLibraryList.push(["Calibre® Auto-Waivers™ User’s and Reference Manual","calbr_autowaiver_useref"] );
   mLibraryList.push(["Calibre® AutoFix User’s Manual","calbr_autofix_user"] );
   mLibraryList.push(["Calibre® CMP Model Builder User’s and Reference Manual","calbr_cmp_model_useref"] );
   mLibraryList.push(["Calibre® CMPAnalyzer User’s Manual","calbr_cmpanalyzer_user"] );
   mLibraryList.push(["Calibre® CellArray RET User’s and Reference Manual","calbr_caret_useref"] );
   mLibraryList.push(["Calibre® Cluster Manager (CalCM) User’s Manual","calbr_cm_user"] );
   mLibraryList.push(["Calibre® DESIGNrev™ Layout Viewer User’s Manual","calbr_drv_user"] );
   mLibraryList.push(["Calibre® DESIGNrev™ Reference Manual","calbr_drv_ref"] );
   mLibraryList.push(["Calibre® DefectClassify™ User’s Manual","calbr_defclass_user"] );
   mLibraryList.push(["Calibre® DefectReview™ User’s Manual","calbr_defrev_user"] );
   mLibraryList.push(["Calibre® Directed Self-Assembly User’s and Reference Manual","calbr_dsa_useref"] );
   mLibraryList.push(["Calibre® Dynamic Resource Allocator (DRA) User’s Manual","calbr_dra_user"] );
   mLibraryList.push(["Calibre® Interactive™ (New GUI) User’s Manual","calbr_interactive_n_user"] );
   mLibraryList.push(["Calibre® Interactive™ User’s Manual","calbr_interactive_user"] );
   mLibraryList.push(["Calibre® Job Deck Editor User’s Manual","calbr_jde_user"] );
   mLibraryList.push(["Calibre® LSG for Synthetic Layout Generation User’s Manual","calbr_lsg_user"] );
   mLibraryList.push(["Calibre® Layout Comparison and Translation Guide","calbr_lvl_fdi_gd"] );
   mLibraryList.push(["Calibre® Litho-Friendly Design User’s Manual","calbr_lfd_user"] );
   mLibraryList.push(["Calibre® Local Printability Enhancement User’s and Reference Manual","calbr_lpe_useref"] );
   mLibraryList.push(["Calibre® LogView User’s Manual","calbr_logview_user"] );
   mLibraryList.push(["Calibre® MDPAutoClassify™ User’s Manual","calbr_mdpautoclassify_user"] );
   mLibraryList.push(["Calibre® MDPDefectAvoidance™ User’s Manual","calbr_mdpdefav_user"] );
   mLibraryList.push(["Calibre® MDPview™ User’s and Reference Manual","calbr_mdpview_useref"] );
   mLibraryList.push(["Calibre® MPCverify User’s and Reference Manual","calbr_mpcv_useref"] );
   mLibraryList.push(["Calibre® Mask Data Preparation User’s and Reference Manual","calbr_mdp_useref"] );
   mLibraryList.push(["Calibre® Metrology API (MAPI) User’s and Reference Manual","calbr_mapi_useref"] );
   mLibraryList.push(["Calibre® Metrology Interface (CMi) User’s Manual","calbr_cmi_user"] );
   mLibraryList.push(["Calibre® Multi-Patterning User’s and Reference Manual","calbr_mp_useref"] );
   mLibraryList.push(["Calibre® OPCpro™ User’s and Reference Manual","calbr_opcpro_useref"] );
   mLibraryList.push(["Calibre® OPCsbar™ User’s and Reference Manual","calbr_sbar_useref"] );
   mLibraryList.push(["Calibre® OPCverify™ User’s and Reference Manual","calbr_opcv_useref"] );
   mLibraryList.push(["Calibre® PERC™ User’s Manual","calbr_perc_user"] );
   mLibraryList.push(["Calibre® Pattern Matching Reference Manual","calbr_pmatch_ref"] );
   mLibraryList.push(["Calibre® Pattern Matching User’s Manual","calbr_pmatch_user"] );
   mLibraryList.push(["Calibre® Post-Tapeout Flow User’s Manual","calbr_pto_user"] );
   mLibraryList.push(["Calibre® Query Server Manual","calbr_query_user"] );
   mLibraryList.push(["Calibre® RVE™ User’s Manual","calbr_rve_user"] );
   mLibraryList.push(["Calibre® RealTime Custom User’s Manual","calbr_realtime_user"] );
   mLibraryList.push(["Calibre® RealTime Digital User’s Manual","calbr_realtime_digital_user"] );
   mLibraryList.push(["Calibre® Release Highlights","calibre_2021_2_18_rh"] );
   mLibraryList.push(["Calibre® Release Notes","calbr_rn"] );
   mLibraryList.push(["Calibre® Rule-Based OPC User’s and Reference Manual","calbr_rbopc_useref"] );
   mLibraryList.push(["Calibre® SMO RET Selection User’s and Reference Manual","calbr_ret_smo_useref"] );
   mLibraryList.push(["Calibre® SONR™ User’s and Reference Manual","calbr_sonr_useref"] );
   mLibraryList.push(["Calibre® SVRFencrypt User’s Manual","calbr_svrfencrypt_user"] );
   mLibraryList.push(["Calibre® Solutions for Physical Verification","calbr_solns_pv_user"] );
   mLibraryList.push(["Calibre® TVFencrypt User’s Manual","calbr_tvfencrypt_user"] );
   mLibraryList.push(["Calibre® Verification User’s Manual","calbr_ver_user"] );
   mLibraryList.push(["Calibre® WORKbench™ Topography Modeling User’s and Reference Manual","calbr_topo_useref"] );
   mLibraryList.push(["Calibre® WORKbench™ User’s and Reference Manual","calbr_wbench_useref"] );
   mLibraryList.push(["Calibre® WORKbench™: RET Flow Tool (RFT) v2.0 User’s Manual","calbr_rftv2_user"] );
   mLibraryList.push(["Calibre® WORKbench™: RET Flow Tool User’s Manual","calbr_rft_user"] );
   mLibraryList.push(["Calibre® YieldAnalyzer and YieldEnhancer User’s and Reference Manual","calbr_yaye_ref"] );
   mLibraryList.push(["Calibre® YieldServer Reference Manual","calbr_ys_ref"] );
   mLibraryList.push(["Calibre® nmMPC™ and Calibre® nmCLMPC User’s and Reference Manual","calbr_nmmpc_useref"] );
   mLibraryList.push(["Calibre® nmModelflow™ User’s and Reference Manual","calbr_nmmdf_useref"] );
   mLibraryList.push(["Calibre® nmOPC™ User’s and Reference Manual","calbr_nmopc_useref"] );
   mLibraryList.push(["Calibre® nmSRAF™ User’s and Reference Manual","calbr_nmsraf_useref"] );
   mLibraryList.push(["Calibre® pxOPC™ User’s and Reference Manual","calbr_pxopc_useref"] );
   mLibraryList.push(["Calibre® xACT™ User’s Manual","xact_user"] );
   mLibraryList.push(["Calibre® xL User’s Manual","calbr_xl_user"] );
   mLibraryList.push(["Calibre® xRC™ User’s Manual","xrc_user"] );
   mLibraryList.push(["DFM Data Analysis User’s and Reference Manual","dfmda_useref"] );
   mLibraryList.push(["FLEXnet License Administration Guide","flexnet_lic_admin","pdf"] );
   mLibraryList.push(["Getting Started with Calibre® Video Series","calbr_gs"] );
   mLibraryList.push(["Licensing Mentor Graphics Software","mgc_licen","pdf"] );
   mLibraryList.push(["Open Artwork System Interchange Standard (OASIS®)","calbr_oasis_gd"] );
   mLibraryList.push(["Siemens® Software and Mentor® Documentation System","mgc_html_help"] );
   mLibraryList.push(["Standard Verification Rule Format (SVRF) Manual","svrf_ur"] );
   mLibraryList.push(["xCalibrate™ Batch User’s Manual","xcalibrat_batch_user"] );
